# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Wesley Dias"
description: > # this means to ignore newlines until "email:"
   Programming Perls

email: wesley_luann@yahoo.com.br
#blog logo
logo: "/assets/images/favicon2.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background.webp"

name: 'Wesley Dias'
author: 'Wesley Dias'
author_image: "/assets/images/profile.jpg"

paginate:	5

url: "http://blog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@TheWesDias'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-129032903-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/TheWesDias
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/TheWesDias
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
